version: '3.9'
services:
  api-java:
    build: ./java-api
    ports:
      - "8080:8080"
    depends_on:
      - prophet-infer
    volumes:
      - ./models/onnx:/app/models/onnx:ro
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx1024m

  prophet-infer:
    build: ./python
    command: ["python", "app_prophet.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./models/prophet:/app/models/prophet:ro
